USE travelGame;

INSERT INTO Continent (name)
VALUES ('Africa'),
       ('Antarctica'),
       ('Asia'),
       ('Europe'),
       ('North America'),
       ('Oceania'),
       ('South America');

INSERT INTO Country (name, continent_id)
VALUES ('Afghanistan', 3),
       ('Albania', 4),
       ('Algeria', 1),
       ('Andorra', 4),
       ('Angola', 1),
       ('Antigua and Barbuda', 5),
       ('Argentina', 7),
       ('Armenia', 3),
       ('Australia', 6),
       ('Austria', 4),
       ('Azerbaijan', 3),
       ('Bahamas', 5),
       ('Bahrain', 3),
       ('Bangladesh', 3),
       ('Barbados', 5),
       ('Belarus', 4),
       ('Belgium', 4),
       ('Belize', 5),
       ('Benin', 1),
       ('Bhutan', 3),
       ('Bolivia', 7),
       ('Bosnia and Herzegovina', 4),
       ('Botswana', 1),
       ('Brazil', 7),
       ('Brunei', 3),
       ('Bulgaria', 4),
       ('Burkina Faso', 1),
       ('Burundi', 1),
       ('Côte d''Ivoire', 1),
       ('Cabo Verde', 1),
       ('Cambodia', 3),
       ('Cameroon', 1),
       ('Canada', 5),
       ('Central African Republic', 1),
       ('Chad', 1),
       ('Chile', 7),
       ('China', 3),
       ('Colombia', 7),
       ('Comoros', 1),
       ('Costa Rica', 5),
       ('Croatia', 4),
       ('Cuba', 5),
       ('Cyprus', 4),
       ('Czech Republic', 4),
       ('Democratic Republic of the Congo', 1),
       ('Denmark', 4),
       ('Djibouti', 1),
       ('Dominica', 5),
       ('Dominican Republic', 5),
       ('Ecuador', 7),
       ('Egypt', 1),
       ('El Salvador', 5),
       ('Equatorial Guinea', 1),
       ('Eritrea', 1),
       ('Estonia', 4),
       ('Eswatini', 1),
       ('Ethiopia', 1),
       ('Fiji', 6),
       ('Finland', 4),
       ('France', 4),
       ('Gabon', 1),
       ('Gambia', 1),
       ('Georgia', 3),
       ('Germany', 4),
       ('Ghana', 1),
       ('Greece', 4),
       ('Grenada', 7),
       ('Guatemala', 5),
       ('Guinea', 1),
       ('Guinea-Bissau', 1),
       ('Guyana', 7),
       ('Haiti', 5),
       ('Honduras', 5),
       ('Hungary', 4),
       ('Iceland', 4),
       ('India', 3),
       ('Indonesia', 3),
       ('Iran', 3),
       ('Iraq', 3),
       ('Ireland', 4),
       ('Israel', 3),
       ('Italy', 4),
       ('Jamaica', 5),
       ('Japan', 3),
       ('Jordan', 3),
       ('Kazakhstan', 3),
       ('Kenya', 1),
       ('Kiribati', 6),
       ('Kuwait', 3),
       ('Kyrgyzstan', 3),
       ('Laos', 3),
       ('Latvia', 4),
       ('Lebanon', 3),
       ('Lesotho', 1),
       ('Liberia', 1),
       ('Libya', 1),
       ('Liechtenstein', 4),
       ('Lithuania', 4),
       ('Luxembourg', 4),
       ('Madagascar', 1),
       ('Malawi', 1),
       ('Malaysia', 3),
       ('Maldives', 3),
       ('Mali', 1),
       ('Malta', 4),
       ('Marshall Islands', 6),
       ('Mauritania', 1),
       ('Mauritius', 1),
       ('Mexico', 5),
       ('Micronesia', 6),
       ('Moldova', 4),
       ('Monaco', 4),
       ('Mongolia', 3),
       ('Montenegro', 4),
       ('Morocco', 1),
       ('Mozambique', 1),
       ('Myanmar', 3),
       ('Namibia', 1),
       ('Nauru', 6),
       ('Nepal', 3),
       ('Netherlands', 4),
       ('New Zealand', 6),
       ('Nicaragua', 5),
       ('Niger', 1),
       ('Nigeria', 1),
       ('North Korea', 3),
       ('North Macedonia', 4),
       ('Norway', 4),
       ('Oman', 3),
       ('Pakistan', 3),
       ('Palau', 6),
       ('Panama', 5),
       ('Papua New Guinea', 6),
       ('Paraguay', 7),
       ('Peru', 7),
       ('Philippines', 3),
       ('Poland', 4),
       ('Portugal', 4),
       ('Qatar', 3),
       ('Romania', 4),
       ('Russia', 4),
       ('Rwanda', 1),
       ('Saint Kitts and Nevis', 5),
       ('Saint Lucia', 5),
       ('Saint Vincent and the Grenadines', 5),
       ('Samoa', 6),
       ('San Marino', 4),
       ('Sao Tome and Principe', 1),
       ('Saudi Arabia', 3),
       ('Senegal', 1),
       ('Serbia', 4),
       ('Seychelles', 1),
       ('Sierra Leone', 1),
       ('Singapore', 3),
       ('Slovakia', 4),
       ('Slovenia', 4),
       ('Solomon Islands', 6),
       ('Somalia', 1),
       ('South Africa', 1),
       ('South Sudan', 1),
       ('Spain', 4),
       ('Sri Lanka', 3),
       ('Sudan', 1),
       ('Suriname', 7),
       ('Sweden', 4),
       ('Switzerland', 4),
       ('Syria', 3),
       ('Taiwan', 3),
       ('Tajikistan', 3),
       ('Tanzania', 1),
       ('Thailand', 3),
       ('Timor-Leste', 3),
       ('Togo', 1),
       ('Tonga', 6),
       ('Trinidad and Tobago', 5),
       ('Tunisia', 1),
       ('Turkey', 3),
       ('Turkmenistan', 3),
       ('Tuvalu', 6),
       ('Uganda', 1),
       ('Ukraine', 4),
       ('United Arab Emirates', 3),
       ('United Kingdom', 4),
       ('United States of America', 5),
       ('Uruguay', 7),
       ('Uzbekistan', 3),
       ('Vanuatu', 6),
       ('Vatican City', 4),
       ('Venezuela', 7),
       ('Vietnam', 3),
       ('Yemen', 3),
       ('Zambia', 1),
       ('Zimbabwe', 1);

-- CAPITAL

INSERT INTO Location (name, type, country_id)
VALUES ('Kabul', 'CAPITAL', 1),
       ('Tirana', 'CAPITAL', 2),
       ('Algiers', 'CAPITAL', 3),
       ('Andorra la Vella', 'CAPITAL', 4),
       ('Luanda', 'CAPITAL', 5),
       ('St. John''s', 'CAPITAL', 6),
       ('Buenos Aires', 'CAPITAL', 7),
       ('Yerevan', 'CAPITAL', 8),
       ('Canberra', 'CAPITAL', 9),
       ('Vienna', 'CAPITAL', 10),
       ('Baku', 'CAPITAL', 11),
       ('Nassau', 'CAPITAL', 12),
       ('Manama', 'CAPITAL', 13),
       ('Dhaka', 'CAPITAL', 14),
       ('Bridgetown', 'CAPITAL', 15),
       ('Minsk', 'CAPITAL', 16),
       ('Brussels', 'CAPITAL', 17),
       ('Belmopan', 'CAPITAL', 18),
       ('Porto-Novo', 'CAPITAL', 19),
       ('Thimphu', 'CAPITAL', 20),
       ('Sucre', 'CAPITAL', 21),
       ('Sarajevo', 'CAPITAL', 22),
       ('Gaborone', 'CAPITAL', 23),
       ('Brasília', 'CAPITAL', 24),
       ('Bandar Seri Begawan', 'CAPITAL', 25),
       ('Sofia', 'CAPITAL', 26),
       ('Ouagadougou', 'CAPITAL', 27),
       ('Gitega', 'CAPITAL', 28),
       ('Yamoussoukro', 'CAPITAL', 29),
       ('Praia', 'CAPITAL', 30),
       ('Phnom Penh', 'CAPITAL', 31),
       ('Yaoundé', 'CAPITAL', 32),
       ('Ottawa', 'CAPITAL', 33),
       ('Bangui', 'CAPITAL', 34),
       ('N''Djamena', 'CAPITAL', 35),
       ('Santiago', 'CAPITAL', 36),
       ('Beijing', 'CAPITAL', 37),
       ('Bogotá', 'CAPITAL', 38),
       ('Moroni', 'CAPITAL', 39),
       ('San José', 'CAPITAL', 40),
       ('Zagreb', 'CAPITAL', 41),
       ('Havana', 'CAPITAL', 42),
       ('Nicosia', 'CAPITAL', 43),
       ('Prague', 'CAPITAL', 44),
       ('Kinshasa', 'CAPITAL', 45),
       ('Copenhagen', 'CAPITAL', 46),
       ('Djibouti', 'CAPITAL', 47),
       ('Roseau', 'CAPITAL', 48),
       ('Santo Domingo', 'CAPITAL', 49),
       ('Quito', 'CAPITAL', 50),
       ('Cairo', 'CAPITAL', 51),
       ('San Salvador', 'CAPITAL', 52),
       ('Malabo', 'CAPITAL', 53),
       ('Asmara', 'CAPITAL', 54),
       ('Tallinn', 'CAPITAL', 55),
       ('Mbabane', 'CAPITAL', 56),
       ('Addis Ababa', 'CAPITAL', 57),
       ('Suva', 'CAPITAL', 58),
       ('Helsinki', 'CAPITAL', 59),
       ('Paris', 'CAPITAL', 60),
       ('Libreville', 'CAPITAL', 61),
       ('Banjul', 'CAPITAL', 62),
       ('Tbilisi', 'CAPITAL', 63),
       ('Berlin', 'CAPITAL', 64),
       ('Accra', 'CAPITAL', 65),
       ('Athens', 'CAPITAL', 66),
       ('St. George''s', 'CAPITAL', 67),
       ('Guatemala City', 'CAPITAL', 68),
       ('Conakry', 'CAPITAL', 69),
       ('Bissau', 'CAPITAL', 70),
       ('Georgetown', 'CAPITAL', 71),
       ('Port-au-Prince', 'CAPITAL', 72),
       ('Tegucigalpa', 'CAPITAL', 73),
       ('Budapest', 'CAPITAL', 74),
       ('Reykjavík', 'CAPITAL', 75),
       ('New Delhi', 'CAPITAL', 76),
       ('Jakarta', 'CAPITAL', 77),
       ('Tehran', 'CAPITAL', 78),
       ('Baghdad', 'CAPITAL', 79),
       ('Dublin', 'CAPITAL', 80),
       ('Jerusalem', 'CAPITAL', 81),
       ('Rome', 'CAPITAL', 82),
       ('Kingston', 'CAPITAL', 83),
       ('Tokyo', 'CAPITAL', 84),
       ('Amman', 'CAPITAL', 85),
       ('Astana', 'CAPITAL', 86),
       ('Nairobi', 'CAPITAL', 87),
       ('South Tarawa', 'CAPITAL', 88),
       ('Kuwait City', 'CAPITAL', 89),
       ('Bishkek', 'CAPITAL', 90),
       ('Vientiane', 'CAPITAL', 91),
       ('Riga', 'CAPITAL', 92),
       ('Beirut', 'CAPITAL', 93),
       ('Maseru', 'CAPITAL', 94),
       ('Monrovia', 'CAPITAL', 95),
       ('Tripoli', 'CAPITAL', 96),
       ('Vaduz', 'CAPITAL', 97),
       ('Vilnius', 'CAPITAL', 98),
       ('Luxembourg', 'CAPITAL', 99),
       ('Antananarivo', 'CAPITAL', 100),
       ('Lilongwe', 'CAPITAL', 101),
       ('Kuala Lumpur', 'CAPITAL', 102),
       ('Malé', 'CAPITAL', 103),
       ('Bamako', 'CAPITAL', 104),
       ('Valletta', 'CAPITAL', 105),
       ('Majuro', 'CAPITAL', 106),
       ('Nouakchott', 'CAPITAL', 107),
       ('Port Louis', 'CAPITAL', 108),
       ('Mexico City', 'CAPITAL', 109),
       ('Palikir', 'CAPITAL', 110),
       ('Chișinău', 'CAPITAL', 111),
       ('Monaco', 'CAPITAL', 112),
       ('Ulaanbaatar', 'CAPITAL', 113),
       ('Podgorica', 'CAPITAL', 114),
       ('Rabat', 'CAPITAL', 115),
       ('Maputo', 'CAPITAL', 116),
       ('Naypyidaw', 'CAPITAL', 117),
       ('Windhoek', 'CAPITAL', 118),
       ('Yaren', 'CAPITAL', 119),
       ('Kathmandu', 'CAPITAL', 120),
       ('Amsterdam', 'CAPITAL', 121),
       ('Wellington', 'CAPITAL', 122),
       ('Managua', 'CAPITAL', 123),
       ('Niamey', 'CAPITAL', 124),
       ('Abuja', 'CAPITAL', 125),
       ('Pyongyang', 'CAPITAL', 126),
       ('Skopje', 'CAPITAL', 127),
       ('Oslo', 'CAPITAL', 128),
       ('Muscat', 'CAPITAL', 129),
       ('Islamabad', 'CAPITAL', 130),
       ('Ngerulmud', 'CAPITAL', 131),
       ('Panama City', 'CAPITAL', 132),
       ('Port Moresby', 'CAPITAL', 133),
       ('Asunción', 'CAPITAL', 134),
       ('Lima', 'CAPITAL', 135),
       ('Manila', 'CAPITAL', 136),
       ('Warsaw', 'CAPITAL', 137),
       ('Lisbon', 'CAPITAL', 138),
       ('Doha', 'CAPITAL', 139),
       ('Bucharest', 'CAPITAL', 140),
       ('Moscow', 'CAPITAL', 141),
       ('Kigali', 'CAPITAL', 142),
       ('Basseterre', 'CAPITAL', 143),
       ('Castries', 'CAPITAL', 144),
       ('Kingstown', 'CAPITAL', 145),
       ('Apia', 'CAPITAL', 146),
       ('San Marino', 'CAPITAL', 147),
       ('São Tomé', 'CAPITAL', 148),
       ('Riyadh', 'CAPITAL', 149),
       ('Dakar', 'CAPITAL', 150),
       ('Belgrade', 'CAPITAL', 151),
       ('Victoria', 'CAPITAL', 152),
       ('Freetown', 'CAPITAL', 153),
       ('Singapore', 'CAPITAL', 154),
       ('Bratislava', 'CAPITAL', 155),
       ('Ljubljana', 'CAPITAL', 156),
       ('Honiara', 'CAPITAL', 157),
       ('Mogadishu', 'CAPITAL', 158),
       ('Pretoria', 'CAPITAL', 159),
       ('Juba', 'CAPITAL', 160),
       ('Madrid', 'CAPITAL', 161),
       ('Colombo', 'CAPITAL', 162),
       ('Khartoum', 'CAPITAL', 163),
       ('Paramaribo', 'CAPITAL', 164),
       ('Stockholm', 'CAPITAL', 165),
       ('Bern', 'CAPITAL', 166),
       ('Damascus', 'CAPITAL', 167),
       ('Taipei', 'CAPITAL', 168),
       ('Dushanbe', 'CAPITAL', 169),
       ('Dodoma', 'CAPITAL', 170),
       ('Bangkok', 'CAPITAL', 171),
       ('Dili', 'CAPITAL', 172),
       ('Lomé', 'CAPITAL', 173),
       ('Nukuʻalofa', 'CAPITAL', 174),
       ('Port of Spain', 'CAPITAL', 175),
       ('Tunis', 'CAPITAL', 176),
       ('Ankara', 'CAPITAL', 177),
       ('Ashgabat', 'CAPITAL', 178),
       ('Funafuti', 'CAPITAL', 179),
       ('Kampala', 'CAPITAL', 180),
       ('Kyiv', 'CAPITAL', 181),
       ('Abu Dhabi', 'CAPITAL', 182),
       ('London', 'CAPITAL', 183),
       ('Washington, D.C.', 'CAPITAL', 184),
       ('Montevideo', 'CAPITAL', 185),
       ('Tashkent', 'CAPITAL', 186),
       ('Port Vila', 'CAPITAL', 187),
       ('Vatican City', 'CAPITAL', 188),
       ('Caracas', 'CAPITAL', 189),
       ('Hanoi', 'CAPITAL', 190),
       ('Sana''a', 'CAPITAL', 191),
       ('Lusaka', 'CAPITAL', 192),
       ('Harare', 'CAPITAL', 193);

-- CITY

INSERT INTO Location (name, type, country_id)
VALUES ('Kandahar', 'CITY', 1),
       ('Herat', 'CITY', 1),
       ('Mazar-e Sharif', 'CITY', 1),
       ('Durrës', 'CITY', 2),
       ('Vlorë', 'CITY', 2),
       ('Oran', 'CITY', 3),
       ('Constantine', 'CITY', 3),
       ('Lubango', 'CITY', 5),
       ('Huambo', 'CITY', 5),
       ('Benguela', 'CITY', 5),
       ('Córdoba', 'CITY', 7),
       ('Rosario', 'CITY', 7),
       ('Mendoza', 'CITY', 7),
       ('Gyumri', 'CITY', 8),
       ('Vanadzor', 'CITY', 8),
       ('Melbourne', 'CITY', 9),
       ('Sydney', 'CITY', 9),
       ('Brisbane', 'CITY', 9),
       ('Perth', 'CITY', 9),
       ('Adelaide', 'CITY', 9),
       ('Gold Coast', 'CITY', 9),
       ('Newcastle', 'CITY', 9),
       ('Wollongong', 'CITY', 9),
       ('Hobart', 'CITY', 9),
       ('Darwin', 'CITY', 9),
       ('Graz', 'CITY', 10),
       ('Linz', 'CITY', 10),
       ('Salzburg', 'CITY', 10),
       ('Innsbruck', 'CITY', 10),
       ('Klagenfurt', 'CITY', 10),
       ('Villach', 'CITY', 10),
       ('Wels', 'CITY', 10),
       ('St. Pölten', 'CITY', 10),
       ('Ganja', 'CITY', 11),
       ('Sumqayit', 'CITY', 11),
       ('Mingachevir', 'CITY', 11),
       ('Chittagong', 'CITY', 14),
       ('Khulna', 'CITY', 14),
       ('Rajshahi', 'CITY', 14),
       ('Gomel', 'CITY', 16),
       ('Mogilev', 'CITY', 16),
       ('Vitebsk', 'CITY', 16),
       ('Antwerp', 'CITY', 17),
       ('Ghent', 'CITY', 17),
       ('Charleroi', 'CITY', 17),
       ('Liège', 'CITY', 17),
       ('Bruges', 'CITY', 17),
       ('Leuven', 'CITY', 17),
       ('Namur', 'CITY', 17),
       ('Mons', 'CITY', 17),
       ('Belize City', 'CITY', 18),
       ('Cotonou', 'CITY', 19),
       ('Parakou', 'CITY', 19),
       ('Djougou', 'CITY', 19),
       ('Phuntsholing', 'CITY', 20),
       ('Punakha', 'CITY', 20),
       ('Santa Cruz', 'CITY', 21),
       ('Cochabamba', 'CITY', 21),
       ('El Alto', 'CITY', 21),
       ('Banja Luka', 'CITY', 22),
       ('Mostar', 'CITY', 22),
       ('Tuzla', 'CITY', 22),
       ('Francistown', 'CITY', 23),
       ('Maun', 'CITY', 23),
       ('São Paulo', 'CITY', 24),
       ('Rio de Janeiro', 'CITY', 24),
       ('Belo Horizonte', 'CITY', 24),
       ('Salvador', 'CITY', 24),
       ('Fortaleza', 'CITY', 24),
       ('Curitiba', 'CITY', 24),
       ('Manaus', 'CITY', 24),
       ('Recife', 'CITY', 24),
       ('Porto Alegre', 'CITY', 24),
       ('Goiânia', 'CITY', 24),
       ('Belém', 'CITY', 24),
       ('Plovdiv', 'CITY', 26),
       ('Varna', 'CITY', 26),
       ('Burgas', 'CITY', 26),
       ('Ruse', 'CITY', 26),
       ('Stara Zagora', 'CITY', 26),
       ('Bobo-Dioulasso', 'CITY', 27),
       ('Gitega', 'CITY', 28),
       ('Muyinga', 'CITY', 28),
       ('Ngozi', 'CITY', 28),
       ('Abidjan', 'CITY', 29),
       ('Bouaké', 'CITY', 29),
       ('San-Pédro', 'CITY', 29),
       ('Daloa', 'CITY', 29),
       ('Mindelo', 'CITY', 30),
       ('Santa Maria', 'CITY', 30),
       ('Espargos', 'CITY', 30),
       ('Battambang', 'CITY', 31),
       ('Siem Reap', 'CITY', 31),
       ('Sihanoukville', 'CITY', 31),
       ('Douala', 'CITY', 32),
       ('Garoua', 'CITY', 32),
       ('Bamenda', 'CITY', 32),
       ('Toronto', 'CITY', 33),
       ('Montreal', 'CITY', 33),
       ('Vancouver', 'CITY', 33),
       ('Calgary', 'CITY', 33),
       ('Edmonton', 'CITY', 33),
       ('Quebec City', 'CITY', 33),
       ('Winnipeg', 'CITY', 33),
       ('Hamilton', 'CITY', 33),
       ('Bimbo', 'CITY', 34),
       ('Berbérati', 'CITY', 34),
       ('Carnot', 'CITY', 34),
       ('Moundou', 'CITY', 35),
       ('Sarh', 'CITY', 35),
       ('Abéché', 'CITY', 35),
       ('Valparaíso', 'CITY', 36),
       ('Concepción', 'CITY', 36),
       ('La Serena', 'CITY', 36),
       ('Antofagasta', 'CITY', 36),
       ('Shanghai', 'CITY', 37),
       ('Chongqing', 'CITY', 37),
       ('Guangzhou', 'CITY', 37),
       ('Tianjin', 'CITY', 37),
       ('Shenzhen', 'CITY', 37),
       ('Chengdu', 'CITY', 37),
       ('Xi’an', 'CITY', 37),
       ('Wuhan', 'CITY', 37),
       ('Hong Kong', 'CITY', 37),
       ('Nanjing', 'CITY', 37),
       ('Hangzhou', 'CITY', 37),
       ('Harbin', 'CITY', 37),
       ('Shenyang', 'CITY', 37),
       ('Qingdao', 'CITY', 37),
       ('Dalian', 'CITY', 37),
       ('Jinan', 'CITY', 37),
       ('Changsha', 'CITY', 37),
       ('Kunming', 'CITY', 37),
       ('Medellín', 'CITY', 38),
       ('Cali', 'CITY', 38),
       ('Barranquilla', 'CITY', 38),
       ('Bucaramanga', 'CITY', 38),
       ('Cartagena', 'CITY', 38),
       ('Pereira', 'CITY', 38),
       ('Mutsamudu', 'CITY', 39),
       ('Fomboni', 'CITY', 39),
       ('Alajuela', 'CITY', 40),
       ('Heredia', 'CITY', 40),
       ('Cartago', 'CITY', 40),
       ('Limón', 'CITY', 40),
       ('Split', 'CITY', 41),
       ('Rijeka', 'CITY', 41),
       ('Osijek', 'CITY', 41),
       ('Zadar', 'CITY', 41),
       ('Santiago de Cuba', 'CITY', 42),
       ('Camagüey', 'CITY', 42),
       ('Holguín', 'CITY', 42),
       ('Santa Clara', 'CITY', 42),
       ('Brno', 'CITY', 44),
       ('Ostrava', 'CITY', 44),
       ('Lubumbashi', 'CITY', 45),
       ('Mbuji-Mayi', 'CITY', 45),
       ('Kananga', 'CITY', 45),
       ('Kisangani', 'CITY', 45),
       ('Aarhus', 'CITY', 46),
       ('Odense', 'CITY', 46),
       ('Aalborg', 'CITY', 46),
       ('Santiago de los Caballeros', 'CITY', 49),
       ('La Romana', 'CITY', 49),
       ('San Pedro de Macorís', 'CITY', 49),
       ('Guayaquil', 'CITY', 50),
       ('Cuenca', 'CITY', 50),
       ('Santo Domingo', 'CITY', 50),
       ('Alexandria', 'CITY', 51),
       ('Giza', 'CITY', 51),
       ('Shubra El-Kheima', 'CITY', 51),
       ('Santa Ana', 'CITY', 52),
       ('San Miguel', 'CITY', 52),
       ('Soyapango', 'CITY', 52),
       ('Santa Tecla', 'CITY', 52),
       ('Bata', 'CITY', 53),
       ('Keren', 'CITY', 54),
       ('Massawa', 'CITY', 54),
       ('Mendefera', 'CITY', 54),
       ('Tartu', 'CITY', 55),
       ('Narva', 'CITY', 55),
       ('Pärnu', 'CITY', 55),
       ('Manzini', 'CITY', 56),
       ('Big Bend', 'CITY', 56),
       ('Piggs Peak', 'CITY', 56),
       ('Dire Dawa', 'CITY', 57),
       ('Mekelle', 'CITY', 57),
       ('Gondar', 'CITY', 57),
       ('Lautoka', 'CITY', 58),
       ('Nadi', 'CITY', 58),
       ('Labasa', 'CITY', 58),
       ('Espoo', 'CITY', 59),
       ('Tampere', 'CITY', 59),
       ('Vantaa', 'CITY', 59),
       ('Oulu', 'CITY', 59),
       ('Turku', 'CITY', 59),
       ('Jyväskylä', 'CITY', 59),
       ('Lahti', 'CITY', 59),
       ('Kuopio', 'CITY', 59),
       ('Kouvola', 'CITY', 59),
       ('Pori', 'CITY', 59),
       ('Marseille', 'CITY', 60),
       ('Lyon', 'CITY', 60),
       ('Toulouse', 'CITY', 60),
       ('Nice', 'CITY', 60),
       ('Nantes', 'CITY', 60),
       ('Strasbourg', 'CITY', 60),
       ('Montpellier', 'CITY', 60),
       ('Bordeaux', 'CITY', 60),
       ('Lille', 'CITY', 60),
       ('Rennes', 'CITY', 60),
       ('Reims', 'CITY', 60),
       ('Le Havre', 'CITY', 60),
       ('Port-Gentil', 'CITY', 61),
       ('Franceville', 'CITY', 61),
       ('Oyem', 'CITY', 61),
       ('Moanda', 'CITY', 61),
       ('Serekunda', 'CITY', 62),
       ('Brikama', 'CITY', 62),
       ('Bakau', 'CITY', 62),
       ('Kutaisi', 'CITY', 63),
       ('Batumi', 'CITY', 63),
       ('Rustavi', 'CITY', 63),
       ('Hamburg', 'CITY', 64),
       ('Munich', 'CITY', 64),
       ('Cologne', 'CITY', 64),
       ('Frankfurt', 'CITY', 64),
       ('Stuttgart', 'CITY', 64),
       ('Düsseldorf', 'CITY', 64),
       ('Dortmund', 'CITY', 64),
       ('Essen', 'CITY', 64),
       ('Leipzig', 'CITY', 64),
       ('Bremen', 'CITY', 64),
       ('Dresden', 'CITY', 64),
       ('Hanover', 'CITY', 64),
       ('Kumasi', 'CITY', 65),
       ('Tamale', 'CITY', 65),
       ('Sekondi-Takoradi', 'CITY', 65),
       ('Ashaiman', 'CITY', 65),
       ('Thessaloniki', 'CITY', 66),
       ('Patras', 'CITY', 66),
       ('Heraklion', 'CITY', 66),
       ('Larissa', 'CITY', 66),
       ('Gouyave', 'CITY', 67),
       ('Grenville', 'CITY', 67),
       ('Sauteurs', 'CITY', 67),
       ('Mixco', 'CITY', 68),
       ('Quetzaltenango', 'CITY', 68),
       ('Escuintla', 'CITY', 68),
       ('Villa Nueva', 'CITY', 68),
       ('Nzérékoré', 'CITY', 69),
       ('Kankan', 'CITY', 69),
       ('Kindia', 'CITY', 69),
       ('Bafatá', 'CITY', 70),
       ('Gabú', 'CITY', 70),
       ('Linden', 'CITY', 71),
       ('New Amsterdam', 'CITY', 71),
       ('Cap-Haïtien', 'CITY', 72),
       ('Carrefour', 'CITY', 72),
       ('Delmas', 'CITY', 72),
       ('San Pedro Sula', 'CITY', 73),
       ('Choloma', 'CITY', 73),
       ('La Ceiba', 'CITY', 73),
       ('Puerto Cortés', 'CITY', 73),
       ('Debrecen', 'CITY', 74),
       ('Szeged', 'CITY', 74),
       ('Miskolc', 'CITY', 74),
       ('Pécs', 'CITY', 74),
       ('Kópavogur', 'CITY', 75),
       ('Hafnarfjörður', 'CITY', 75),
       ('Akureyri', 'CITY', 75),
       ('Reykjanesbær', 'CITY', 75),
       ('Garðabær', 'CITY', 75),
       ('Mumbai', 'CITY', 76),
       ('Bangalore', 'CITY', 76),
       ('Hyderabad', 'CITY', 76),
       ('Ahmedabad', 'CITY', 76),
       ('Chennai', 'CITY', 76),
       ('Kolkata', 'CITY', 76),
       ('Surat', 'CITY', 76),
       ('Pune', 'CITY', 76),
       ('Jaipur', 'CITY', 76),
       ('Lucknow', 'CITY', 76),
       ('Surabaya', 'CITY', 77),
       ('Bandung', 'CITY', 77),
       ('Medan', 'CITY', 77),
       ('Semarang', 'CITY', 77),
       ('Palembang', 'CITY', 77),
       ('Makassar', 'CITY', 77),
       ('Bekasi', 'CITY', 77),
       ('Depok', 'CITY', 77),
       ('Tangerang', 'CITY', 77),
       ('South Tangerang', 'CITY', 77),
       ('Mashhad', 'CITY', 78),
       ('Isfahan', 'CITY', 78),
       ('Karaj', 'CITY', 78),
       ('Shiraz', 'CITY', 78),
       ('Tabriz', 'CITY', 78),
       ('Qom', 'CITY', 78),
       ('Ahvaz', 'CITY', 78),
       ('Kermanshah', 'CITY', 78),
       ('Urmia', 'CITY', 78),
       ('Basra', 'CITY', 79),
       ('Mosul', 'CITY', 79),
       ('Erbil', 'CITY', 79),
       ('Kirkuk', 'CITY', 79),
       ('Najaf', 'CITY', 79),
       ('Karbala', 'CITY', 79),
       ('Sulaymaniyah', 'CITY', 79),
       ('Cork', 'CITY', 80),
       ('Limerick', 'CITY', 80),
       ('Galway', 'CITY', 80),
       ('Waterford', 'CITY', 80),
       ('Drogheda', 'CITY', 80),
       ('Tel Aviv', 'CITY', 81),
       ('Haifa', 'CITY', 81),
       ('Rishon LeZion', 'CITY', 81),
       ('Petah Tikva', 'CITY', 81),
       ('Ashdod', 'CITY', 81),
       ('Milan', 'CITY', 82),
       ('Naples', 'CITY', 82),
       ('Turin', 'CITY', 82),
       ('Palermo', 'CITY', 82),
       ('Genoa', 'CITY', 82),
       ('Bologna', 'CITY', 82),
       ('Florence', 'CITY', 82),
       ('Bari', 'CITY', 82),
       ('Catania', 'CITY', 82),
       ('Venice', 'CITY', 82),
       ('Montego Bay', 'CITY', 83),
       ('Spanish Town', 'CITY', 83),
       ('Portmore', 'CITY', 83),
       ('Yokohama', 'CITY', 84),
       ('Osaka', 'CITY', 84),
       ('Nagoya', 'CITY', 84),
       ('Sapporo', 'CITY', 84),
       ('Fukuoka', 'CITY', 84),
       ('Kobe', 'CITY', 84),
       ('Kawasaki', 'CITY', 84),
       ('Kyoto', 'CITY', 84),
       ('Saitama', 'CITY', 84),
       ('Hiroshima', 'CITY', 84),
       ('Zarqa', 'CITY', 85),
       ('Irbid', 'CITY', 85),
       ('Russeifa', 'CITY', 85),
       ('Almaty', 'CITY', 86),
       ('Shymkent', 'CITY', 86),
       ('Karaganda', 'CITY', 86),
       ('Mombasa', 'CITY', 87),
       ('Kisumu', 'CITY', 87),
       ('Nakuru', 'CITY', 87),
       ('Eldoret', 'CITY', 87),
       ('Bikenibeu', 'CITY', 88),
       ('Teaoraereke', 'CITY', 88),
       ('Betio', 'CITY', 88),
       ('Al Ahmadi', 'CITY', 89),
       ('Al Farwaniyah', 'CITY', 89),
       ('Hawalli', 'CITY', 89),
       ('Osh', 'CITY', 90),
       ('Jalal-Abad', 'CITY', 90),
       ('Karakol', 'CITY', 90),
       ('Savannakhet', 'CITY', 91),
       ('Pakse', 'CITY', 91),
       ('Luang Prabang', 'CITY', 91),
       ('Daugavpils', 'CITY', 92),
       ('Liepaja', 'CITY', 92),
       ('Jelgava', 'CITY', 92),
       ('Tripoli', 'CITY', 93),
       ('Sidon', 'CITY', 93),
       ('Tyre', 'CITY', 93),
       ('Teyateyaneng', 'CITY', 94),
       ('Mafeteng', 'CITY', 94),
       ('Hlotse', 'CITY', 94),
       ('Gbarnga', 'CITY', 95),
       ('Kakata', 'CITY', 95),
       ('Buchanan', 'CITY', 95),
       ('Benghazi', 'CITY', 96),
       ('Misrata', 'CITY', 96),
       ('Sabha', 'CITY', 96),
       ('Schaan', 'CITY', 97),
       ('Balzers', 'CITY', 97),
       ('Kaunas', 'CITY', 98),
       ('Klaipėda', 'CITY', 98),
       ('Šiauliai', 'CITY', 98),
       ('Panevėžys', 'CITY', 98),
       ('Esch-sur-Alzette', 'CITY', 99),
       ('Differdange', 'CITY', 99),
       ('Dudelange', 'CITY', 99),
       ('Toamasina', 'CITY', 100),
       ('Antsirabe', 'CITY', 100),
       ('Fianarantsoa', 'CITY', 100),
       ('Mahajanga', 'CITY', 100),
       ('Toliara', 'CITY', 100),
       ('Blantyre', 'CITY', 101),
       ('Mzuzu', 'CITY', 101),
       ('Zomba', 'CITY', 101),
       ('George Town', 'CITY', 102),
       ('Johor Bahru', 'CITY', 102),
       ('Ipoh', 'CITY', 102),
       ('Kota Kinabalu', 'CITY', 102),
       ('Petaling Jaya', 'CITY', 102),
       ('Shah Alam', 'CITY', 102),
       ('Melaka', 'CITY', 102),
       ('Kuching', 'CITY', 102),
       ('Fuvahmulah', 'CITY', 103),
       ('Addu City', 'CITY', 103),
       ('Sikasso', 'CITY', 104),
       ('Koutiala', 'CITY', 104),
       ('Birkirkara', 'CITY', 105),
       ('Sliema', 'CITY', 105),
       ('Majuro Atoll', 'CITY', 106),
       ('Nouadhibou', 'CITY', 107),
       ('Kiffa', 'CITY', 107),
       ('Beau Bassin-Rose Hill', 'CITY', 108),
       ('Vacoas-Phoenix', 'CITY', 108),
       ('Guadalajara', 'CITY', 109),
       ('Monterrey', 'CITY', 109),
       ('Puebla', 'CITY', 109),
       ('Tijuana', 'CITY', 109),
       ('León', 'CITY', 109),
       ('Ciudad Juárez', 'CITY', 109),
       ('Zapopan', 'CITY', 109),
       ('Mérida', 'CITY', 109),
       ('Querétaro', 'CITY', 109),
       ('Cancún', 'CITY', 109),
       ('Weno', 'CITY', 110),
       ('Bălți', 'CITY', 111),
       ('Tiraspol', 'CITY', 111),
       ('Monte Carlo', 'CITY', 112),
       ('Erdenet', 'CITY', 113),
       ('Darkhan', 'CITY', 113),
       ('Nikšić', 'CITY', 114),
       ('Pljevlja', 'CITY', 114),
       ('Casablanca', 'CITY', 115),
       ('Marrakesh', 'CITY', 115),
       ('Fès', 'CITY', 115),
       ('Beira', 'CITY', 116),
       ('Nampula', 'CITY', 116),
       ('Mandalay', 'CITY', 117),
       ('Mawlamyine', 'CITY', 117),
       ('Walvis Bay', 'CITY', 118),
       ('Swakopmund', 'CITY', 118),
       ('Yaren', 'CITY', 119),
       ('Pokhara', 'CITY', 120),
       ('Biratnagar', 'CITY', 120),
       ('Dharan', 'CITY', 120),
       ('Rotterdam', 'CITY', 121),
       ('Eindhoven', 'CITY', 121),
       ('Utrecht', 'CITY', 121),
       ('Groningen', 'CITY', 121),
       ('Auckland', 'CITY', 122),
       ('Christchurch', 'CITY', 122),
       ('Wellington', 'CITY', 122),
       ('Hamilton', 'CITY', 122),
       ('Tauranga', 'CITY', 122),
       ('León', 'CITY', 123),
       ('Masaya', 'CITY', 123),
       ('Chinandega', 'CITY', 123),
       ('Zinder', 'CITY', 124),
       ('Maradi', 'CITY', 124),
       ('Tahoua', 'CITY', 124),
       ('Lagos', 'CITY', 125),
       ('Kano', 'CITY', 125),
       ('Ibadan', 'CITY', 125),
       ('Port Harcourt', 'CITY', 125),
       ('Benin City', 'CITY', 125),
       ('Kaduna', 'CITY', 125),
       ('Enugu', 'CITY', 125),
       ('Hamhung', 'CITY', 126),
       ('Chongjin', 'CITY', 126),
       ('Nampo', 'CITY', 126),
       ('Bitola', 'CITY', 127),
       ('Kumanovo', 'CITY', 127),
       ('Tetovo', 'CITY', 127),
       ('Bergen', 'CITY', 128),
       ('Stavanger', 'CITY', 128),
       ('Trondheim', 'CITY', 128),
       ('Drammen', 'CITY', 128),
       ('Sohar', 'CITY', 129),
       ('Salalah', 'CITY', 129),
       ('Nizwa', 'CITY', 129),
       ('Lahore', 'CITY', 130),
       ('Karachi', 'CITY', 130),
       ('Faisalabad', 'CITY', 130),
       ('Multan', 'CITY', 130),
       ('Rawalpindi', 'CITY', 130),
       ('Koror', 'CITY', 131),
       ('Colón', 'CITY', 132),
       ('David', 'CITY', 132),
       ('Santiago', 'CITY', 132),
       ('Lae', 'CITY', 133),
       ('Madang', 'CITY', 133),
       ('Mount Hagen', 'CITY', 133),
       ('Ciudad del Este', 'CITY', 134),
       ('Encarnación', 'CITY', 134),
       ('Pedro Juan Caballero', 'CITY', 134),
       ('Arequipa', 'CITY', 135),
       ('Trujillo', 'CITY', 135),
       ('Chiclayo', 'CITY', 135),
       ('Callao', 'CITY', 135),
       ('Cebu City', 'CITY', 136),
       ('Davao City', 'CITY', 136),
       ('Iloilo City', 'CITY', 136),
       ('Zamboanga', 'CITY', 136),
       ('Kraków', 'CITY', 137),
       ('Łódź', 'CITY', 137),
       ('Wrocław', 'CITY', 137),
       ('Poznań', 'CITY', 137),
       ('Gdańsk', 'CITY', 137),
       ('Porto', 'CITY', 138),
       ('Braga', 'CITY', 138),
       ('Coimbra', 'CITY', 138),
       ('Funchal', 'CITY', 138),
       ('Al Rayyan', 'CITY', 139),
       ('Umm Salal', 'CITY', 139),
       ('Al Khor', 'CITY', 139),
       ('Cluj-Napoca', 'CITY', 140),
       ('Timișoara', 'CITY', 140),
       ('Iași', 'CITY', 140),
       ('Constanța', 'CITY', 140),
       ('Craiova', 'CITY', 140),
       ('Saint Petersburg', 'CITY', 141),
       ('Novosibirsk', 'CITY', 141),
       ('Yekaterinburg', 'CITY', 141),
       ('Kazan', 'CITY', 141),
       ('Nizhny Novgorod', 'CITY', 141),
       ('Butare', 'CITY', 142),
       ('Gisenyi', 'CITY', 142),
       ('Sandy Point', 'CITY', 143),
       ('Vieux Fort', 'CITY', 144),
       ('Georgetown', 'CITY', 145),
       ('Vaitele', 'CITY', 146),
       ('Serravalle', 'CITY', 147),
       ('Borgo Maggiore', 'CITY', 147),
       ('Santo Amaro', 'CITY', 148),
       ('Trindade', 'CITY', 148),
       ('Jeddah', 'CITY', 149),
       ('Mecca', 'CITY', 149),
       ('Dammam', 'CITY', 149),
       ('Thiès', 'CITY', 150),
       ('Saint-Louis', 'CITY', 150),
       ('Kaolack', 'CITY', 150),
       ('Novi Sad', 'CITY', 151),
       ('Niš', 'CITY', 151),
       ('Kragujevac', 'CITY', 151),
       ('Beau Vallon', 'CITY', 152),
       ('Bo', 'CITY', 153),
       ('Kenema', 'CITY', 153),
       ('Košice', 'CITY', 155),
       ('Prešov', 'CITY', 155),
       ('Žilina', 'CITY', 155),
       ('Maribor', 'CITY', 156),
       ('Celje', 'CITY', 156),
       ('Kranj', 'CITY', 156),
       ('Gizo', 'CITY', 157),
       ('Auki', 'CITY', 157),
       ('Hargeisa', 'CITY', 158),
       ('Berbera', 'CITY', 158),
       ('Kismayo', 'CITY', 158),
       ('Johannesburg', 'CITY', 159),
       ('Cape Town', 'CITY', 159),
       ('Durban', 'CITY', 159),
       ('Port Elizabeth', 'CITY', 159),
       ('Pretoria', 'CITY', 159),
       ('Busan', 'CITY', 160),
       ('Incheon', 'CITY', 160),
       ('Daegu', 'CITY', 160),
       ('Daejeon', 'CITY', 160),
       ('Malakal', 'CITY', 161),
       ('Wau', 'CITY', 161),
       ('Barcelona', 'CITY', 162),
       ('Valencia', 'CITY', 162),
       ('Seville', 'CITY', 162),
       ('Zaragoza', 'CITY', 162),
       ('Málaga', 'CITY', 162),
       ('Kandy', 'CITY', 163),
       ('Galle', 'CITY', 163),
       ('Jaffna', 'CITY', 163),
       ('Omdurman', 'CITY', 164),
       ('Port Sudan', 'CITY', 164),
       ('Gothenburg', 'CITY', 165),
       ('Malmö', 'CITY', 165),
       ('Uppsala', 'CITY', 165),
       ('Västerås', 'CITY', 165),
       ('Örebro', 'CITY', 165),
       ('Linköping', 'CITY', 165),
       ('Helsingborg', 'CITY', 165),
       ('Jönköping', 'CITY', 165),
       ('Norrköping', 'CITY', 165),
       ('Lund', 'CITY', 165),
       ('Umeå', 'CITY', 165),
       ('Gävle', 'CITY', 165),
       ('Borås', 'CITY', 165),
       ('Södertälje', 'CITY', 165),
       ('Eskilstuna', 'CITY', 165),
       ('Karlstad', 'CITY', 165),
       ('Täby', 'CITY', 165),
       ('Sundsvall', 'CITY', 165),
       ('Luleå', 'CITY', 165),
       ('Trollhättan', 'CITY', 165),
       ('Zurich', 'CITY', 166),
       ('Geneva', 'CITY', 166),
       ('Basel', 'CITY', 166),
       ('Lausanne', 'CITY', 166),
       ('Aleppo', 'CITY', 167),
       ('Homs', 'CITY', 167),
       ('Latakia', 'CITY', 167),
       ('Kaohsiung', 'CITY', 168),
       ('Taichung', 'CITY', 168),
       ('Tainan', 'CITY', 168),
       ('Khujand', 'CITY', 169),
       ('Kulob', 'CITY', 169),
       ('Dar es Salaam', 'CITY', 170),
       ('Mwanza', 'CITY', 170),
       ('Arusha', 'CITY', 170),
       ('Chiang Mai', 'CITY', 171),
       ('Pattaya', 'CITY', 171),
       ('Phuket', 'CITY', 171),
       ('Sokodé', 'CITY', 173),
       ('Kara', 'CITY', 173),
       ('Neiafu', 'CITY', 174),
       ('San Fernando', 'CITY', 175),
       ('Chaguanas', 'CITY', 175),
       ('Sfax', 'CITY', 176),
       ('Sousse', 'CITY', 176),
       ('Ettadhamen', 'CITY', 176),
       ('Izmir', 'CITY', 177),
       ('Batman', 'CITY', 177),
       ('Bursa', 'CITY', 177),
       ('Antalya', 'CITY', 177),
       ('Adana', 'CITY', 177),
       ('Gaziantep', 'CITY', 177),
       ('Turkmenabat', 'CITY', 178),
       ('Mary', 'CITY', 178),
       ('Turkmenabat', 'CITY', 179),
       ('Mary', 'CITY', 179),
       ('Gulu', 'CITY', 180),
       ('Mbarara', 'CITY', 180),
       ('Lira', 'CITY', 180),
       ('Kharkiv', 'CITY', 181),
       ('Odesa', 'CITY', 181),
       ('Dnipro', 'CITY', 181),
       ('Donetsk', 'CITY', 181),
       ('Zaporizhzhia', 'CITY', 181),
       ('Dubai', 'CITY', 182),
       ('Sharjah', 'CITY', 182),
       ('Birmingham', 'CITY', 183),
       ('Manchester', 'CITY', 183),
       ('Glasgow', 'CITY', 183),
       ('Liverpool', 'CITY', 183),
       ('Leeds', 'CITY', 183),
       ('Sheffield', 'CITY', 183),
       ('Bradford', 'CITY', 183),
       ('Edinburgh', 'CITY', 183),
       ('Cardiff', 'CITY', 183),
       ('Belfast', 'CITY', 183),
       ('Bristol', 'CITY', 183),
       ('Nottingham', 'CITY', 183),
       ('Leicester', 'CITY', 183),
       ('Coventry', 'CITY', 183),
       ('Hull', 'CITY', 183),
       ('New York', 'CITY', 184),
       ('Los Angeles', 'CITY', 184),
       ('Chicago', 'CITY', 184),
       ('Houston', 'CITY', 184),
       ('Phoenix', 'CITY', 184),
       ('Philadelphia', 'CITY', 184),
       ('San Antonio', 'CITY', 184),
       ('San Diego', 'CITY', 184),
       ('Dallas', 'CITY', 184),
       ('San Jose', 'CITY', 184),
       ('Austin', 'CITY', 184),
       ('Jacksonville', 'CITY', 184),
       ('Fort Worth', 'CITY', 184),
       ('Columbus', 'CITY', 184),
       ('Charlotte', 'CITY', 184),
       ('San Francisco', 'CITY', 184),
       ('Indianapolis', 'CITY', 184),
       ('Seattle', 'CITY', 184),
       ('Denver', 'CITY', 184),
       ('Boston', 'CITY', 184),
       ('El Paso', 'CITY', 184),
       ('Nashville', 'CITY', 184),
       ('Detroit', 'CITY', 184),
       ('Oklahoma City', 'CITY', 184),
       ('Portland', 'CITY', 184),
       ('Las Vegas', 'CITY', 184),
       ('Memphis', 'CITY', 184),
       ('Louisville', 'CITY', 184),
       ('Baltimore', 'CITY', 184),
       ('Samarkand', 'CITY', 186),
       ('Namangan', 'CITY', 186),
       ('Andijan', 'CITY', 186),
       ('Bukhara', 'CITY', 186),
       ('Maracaibo', 'CITY', 189),
       ('Valencia', 'CITY', 189),
       ('Barquisimeto', 'CITY', 189),
       ('Ciudad Guayana', 'CITY', 189),
       ('Ho Chi Minh City', 'CITY', 190),
       ('Da Nang', 'CITY', 190),
       ('Hai Phong', 'CITY', 190),
       ('Can Tho', 'CITY', 190),
       ('Aden', 'CITY', 191),
       ('Taiz', 'CITY', 191),
       ('Al Hudaydah', 'CITY', 191),
       ('Ndola', 'CITY', 192),
       ('Kitwe', 'CITY', 192),
       ('Livingstone', 'CITY', 192),
       ('Bulawayo', 'CITY', 193),
       ('Mutare', 'CITY', 193),
       ('Gweru', 'CITY', 193);

-- SITE

INSERT INTO Location (name, type, country_id)
VALUES ('Iguazú Falls (Argentina Side)', 'SITE', 7),
       ('Sydney Opera House', 'SITE', 9),
       ('Uluru', 'SITE', 9),
       ('Great Barrier Reef', 'SITE', 9),
       ('Sydney Harbour Bridge', 'SITE', 9),
       ('Schönbrunn Palace', 'SITE', 10),
       ('Historic Centre of Bruges', 'SITE', 17),
       ('Okavango Delta', 'SITE', 23),
       ('Christo Redentor', 'SITE', 24),
       ('Estádio do Maracanã', 'SITE', 24),
       ('Iguaçu Falls (Brazil Side)', 'SITE', 24),
       ('Rila Monastery', 'SITE', 26),
       ('CN Tower', 'SITE', 33),
       ('Historic Quarter of Valparaíso', 'SITE', 36),
       ('Moai Statues', 'SITE', 36),
       ('The Great Wall', 'SITE', 37),
       ('Terracotta Army', 'SITE', 37),
       ('Forbidden City', 'SITE', 37),
       ('Potala Palace', 'SITE', 37),
       ('Mount Everest', 'SITE', 37),
       ('Historic Centre of Cartagena', 'SITE', 38),
       ('Plitvice Lakes National Park', 'SITE', 41),
       ('Charles Bridge', 'SITE', 44),
       ('The Little Mermaid', 'SITE', 46),
       ('Tivoli Gardens', 'SITE', 46),
       ('Galápagos Islands', 'SITE', 50),
       ('Great Pyramid of Giza', 'SITE', 51),
       ('Great Sphinx of Giza', 'SITE', 51),
       ('Rock-Hewn Churches of Lalibela', 'SITE', 57),
       ('Eiffel Tower', 'SITE', 60),
       ('Louvre Museum', 'SITE', 60),
       ('Mont Saint-Michel', 'SITE', 60),
       ('Notre Dame Cathedral', 'SITE', 60),
       ('Versailles Palace', 'SITE', 60),
       ('Brandenburg Gate', 'SITE', 64),
       ('Neuschwanstein Castle', 'SITE', 64),
       ('Acropolis of Athens', 'SITE', 66),
       ('Santorini Caldera', 'SITE', 66),
       ('Taj Mahal', 'SITE', 76),
       ('Ellora Caves', 'SITE', 76),
       ('Jaipur City Palace', 'SITE', 76),
       ('Varanasi Ghats', 'SITE', 76),
       ('Mahabodhi Temple', 'SITE', 76),
       ('Meenakshi Temple', 'SITE', 76),
       ('Borobudur', 'SITE', 77),
       ('Persepolis', 'SITE', 78),
       ('Colosseum', 'SITE', 82),
       ('Leaning Tower of Pisa', 'SITE', 82),
       ('Venice Canals', 'SITE', 82),
       ('Kotoku-in', 'SITE', 84),
       ('Himeji Castle', 'SITE', 84),
       ('Mount Fuji', 'SITE', 84),
       ('Jerash Ruins', 'SITE', 85),
       ('Petra', 'SITE', 85),
       ('Petronas Towers', 'SITE', 102),
       ('Timbuktu', 'SITE', 104),
       ('Chichén Itzá', 'SITE', 109),
       ('Teotihuacán', 'SITE', 109),
       ('Palenque', 'SITE', 109),
       ('Nan Madol', 'SITE', 110),
       ('Chefchaouen Medina', 'SITE', 115),
       ('Aït Benhaddou', 'SITE', 115),
       ('Angkor Wat', 'SITE', 117),
       ('Shwedagon Paya', 'SITE', 117),
       ('Gyeongbokgung Palace', 'SITE', 126),
       ('Panama Canal', 'SITE', 132),
       ('Machu Picchu', 'SITE', 135),
       ('Nazca Lines', 'SITE', 135),
       ('Országház', 'SITE', 140),
       ('Winter Palace', 'SITE', 141),
       ('Red Square', 'SITE', 141),
       ('Saint Basil\'s Cathedral', 'SITE', 141),
       ('Bolshoi Theatre', 'SITE', 141),
       ('Sagrada Familia', 'SITE', 161),
       ('Alhambra', 'SITE', 161),
       ('Liseberg', 'SITE', 165),
       ('Poseidon Statue', 'SITE', 165),
       ('Feskekörka', 'SITE', 165),
       ('Serengeti National Park', 'SITE', 170),
       ('Hagia Sophia', 'SITE', 177),
       ('Stonehenge', 'SITE', 183),
       ('Globe Theatre', 'SITE', 183),
       ('Buckingham Palace', 'SITE', 183),
       ('Tower of London', 'SITE', 183),
       ('Edinburgh Castle', 'SITE', 183),
       ('Big Ben', 'SITE', 183),
       ('Statue of Liberty', 'SITE', 184),
       ('Grand Canyon', 'SITE', 184),
       ('Yosemite National Park', 'SITE', 184),
       ('Golden Gate Bridge', 'SITE', 184),
       ('Disneyland', 'SITE', 184),
       ('Alcatraz Island', 'SITE', 184),
       ('Hollywood Sign', 'SITE', 184),
       ('Mt. Rushmore', 'SITE', 184),
       ('Yellowstone National Park', 'SITE', 184),
       ('Niagara Falls', 'SITE', 184),
       ('Apostolic Palace', 'SITE', 188),
       ('Sistine Chapel', 'SITE', 188),
       ('Victoria Falls', 'SITE', 193);

INSERT INTO Transport (type)
VALUES ('Airplane'),
       ('Bike'),
       ('Boat'),
       ('Car'),
       ('Motorbike'),
       ('Train');
